# Generated by Django 5.0.6 on 2024-07-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0007_auto_20201104_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
